### ISSUE TITLE
Add CI/CD using Github Actions

### ISSUE THREAD

**Issue by joswayski** [joswayski/open-ats#53]
Nader tutorial here: https://www.youtube.com/watch?v=iEgeuzKEIFs&t=13s

**Comment by vaish567** [comment]
Howdy @joswayski Can I step up on this issue as this would be my first pull request. Could you please assign me for this issue? :)

**Comment by joswayski** [comment]
:) Thank you!

**Comment by joswayski** [comment]
I fixed some permissions, you should be able to make a PR now!

**Comment by vaish567** [comment]
Hello @joswayski Quick question Should mention aws_key and aws_secret value?

**Comment by joswayski** [comment]
![Screen Shot 2021-06-01 at 4 48 31 PM](https://user-images.githubusercontent.com/22891173/120388555-411d0c00-c2f9-11eb-93f2-52bf6f461d8f.png)
You can leave it like it is in the video, do not put yours as they will be made public!
